### PR TITLE
Multiple updates to RTMP

### PR DESCRIPTION
**Pull request by chriswiggins**
Have done some changes to this plugin which we needed in our environment. Hopefully they're good enough to be merged :-)

 * Adds some build environment fixes (missing CSS, updates loadash.template, swf added to gulp watch path
 * Adds scaling support to the player. Can now specify letterbox, zoom, stretch or none. See README
 * Adds Flash wmode option - required in certain applications to change how the player displays

Let me know if theres any changes required!

### CODE REVIEW

**Comment by chriswiggins** [comment]
Also bumped the version string to `clappr rtmp 0.9-alpha`

**Comment by tarkanlar** [comment]
Thanks Chris, but scaling didn't work for me on chrome the old one fits normally but this version doesn't fit

**Comment by chriswiggins** [comment]
@tarkanlar can you confirm you're using the new RTMP.swf thats located in this pull request? Its in dist/assets/RTMP.swf. You'll also see `clappr rtmp 0.9-alpha` logged in your console if you're using the right version.

If not, just add the following to your player config:

`swfPath: '/path/to/RTMP.swf'`

Let me know how you get on

**Comment by tarkanlar** [comment]
Yep,  i updated RTMP.swf and did that and got clappr rtmp 0.9-alpha logged in console. i updated rtmp.min.js as well but somehow nothing changes when i make letterbox,zoom or stretch.

**Comment by chriswiggins** [comment]
Can you paste your source html? I'll have a look into it for you :-)

**Comment by tarkanlar** [comment]
Yep,

<!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <script type="text/javascript" charset="utf-8" src="/dist/clappr.min.js"></script>
  <script type="text/javascript" charset="utf-8" src="/dist/rtmp.min.js"></script>
  <title> Test </title>
  <script type="text/javascript" charset="utf-8">
window.onload = function() {
  var player = new Clappr.Player({
    sources: ['rtmp://s01.vidpanel.com:1935/demo/demo?type=live'],
    parentId: '#player-wrapper',
    useHardwareVideoDecoder: false,
    autoPlay: true,
    width: 960,
    height:540,
    swfPath:'/assets/RTMP.swf',
    scaling:'stretch',
    wmode: 'opaque',
    channel: 'demo',
    plugins: {
      'playback': [RTMP]
    }
  });
}
  </script>
</head>
<body>
  <div id="player-wrapper">
  </div>
</body>
</html>

**Comment by chriswiggins** [comment]
Thanks @tarkanlar - I've found a problem or two and will fix them and add to this change request. Will try and do this tomorrow at some stage!

Thanks for your help with the testing :-)

**Comment by chriswiggins** [comment]
@tarkanlar Give that a go now. There were the following problems that have now been fixed:
1) I hadn't updated rtmp.min.js so it wasn't loading the latest changes on the JS side
2) I hadn't tested different width and heights when loading the player so some changes were needed there
3) I hadn't tested autoPlay so another few changes needed there.

Let me know how it goes.
Chris

**Comment by tarkanlar** [comment]
Hey @chriswiggins awesome, works fine now.

**Comment by leandromoreira** [comment]
@gfronza did we have all these features already? can we close this or try to merge?

**Comment by gfronza** [comment]
Yes, we do. We can close this one.

**Comment by leandromoreira** [comment]
:) thanks

**Pull request closed without merging**
